version: '3.8'

  networks:
    - camunda-cloud
    - camunda-platform

services:
  camunda:
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:${DISTRO:-7.16.5}
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://camunda-postgres:5432/camunda?user=camunda&password=camunda&characterEncoding=UTF-8&reWriteBatchedInserts=true
    ports:
      - "8080:8080"

  camunda-postgres:
    image: bitnami/postgresql:11.14.0
    restart: always
    environment:
      POSTGRESQL_USER: camunda
      POSTGRESQL_PASSWORD: camunda
      POSTGRESQL_DATABASE: camunda
    ports:
      - "5432:5432"
    networks:
      - camunda-platform
