########################################
# Camunda Platform full development setup
########################################
version: '3.8'

volumes:
  certs:

networks:
  # Note there are two bridge networks. One for Zeebe and one for IAM. Operate, Tasklist, and Optimize use both
  camunda-cloud: { }
  camunda-platform: { }

services:
  ########################################
  # Business Data Service
  ########################################
  data-api:
    container_name: data-api
    image: ghcr.io/camunda-consulting/camunda-demo-data:latest
    # build:
    #   context: ../camunda-demo-data
    ports:
      - "9000:9000"
    volumes:
      - ./certs:/opt/certs
    environment:
      PROFILES: data,user,case,cors,prod
#      DATABASE_URL: jdbc:postgresql://postgres:5432/camunda?user=camunda&password=camunda&characterEncoding=UTF-8&reWriteBatchedInserts=true&ssl=true&sslrootcert=/opt/certs/root.crt&sslcert=/opt/certs/root.crt&sslmode=require
      DATABASE_URL: jdbc:postgresql://postgres:5432/camunda?user=camunda&password=camunda&characterEncoding=UTF-8&reWriteBatchedInserts=true
      DATABASE_DRIVER: org.postgresql.Driver
      PORT: 9000
      MAX_POOL_SIZE: 3
    #      ADMIN_CLIENT_URL: http://camunda-node-1:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
        reservations:
          memory: 1000M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
    restart: always
    networks:
      - camunda-platform
