########################################
# Camunda Platform full development setup
########################################
version: '3.8'

volumes:
  certs:

networks:
  # Note there are two bridge networks. One for Zeebe and one for IAM. Operate, Tasklist, and Optimize use both
  camunda-platform: { }

services:
########################################
# Camunda Platform Service
########################################
  c7-client:
    container_name: c7-client
    image: ghcr.io/camunda-consulting/camunda-demo-c7-client:latest
    #
    # build:
    #   context: ../camunda-7-demo-spring-boot-client
    ports:
      - "9012:8080"
    volumes:
      - ./certs:/opt/certs
    environment:
      PROFILES: cors,prod
      PORT: 8080
      CAMUNDA_API: http://camunda-7:8080/engine-rest/message
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M
        reservations:
          memory: 1000M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://camunda-platform:8080/engine-rest/engine"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - camunda-platform
    depends_on:
      - camunda-7
