########################################
# Camunda Platform full development setup
########################################
version: '3.8'

volumes:
  certs:

networks:
  # Note there are two bridge networks. One for Zeebe and one for IAM. Operate, Tasklist, and Optimize use both
  camunda-cloud: { }
  camunda-platform: { }

services:
  ########################################
  # Business Data Service
  ########################################
  data-api:
    container_name: data-api
    build:
      context: ./camunda-data-api-demo
    ports:
      - "9000:9000"
    volumes:
      - ./certs:/opt/certs
    environment:
      DATABASE_URL: jdbc:postgresql://camunda-postgres:5432/camunda?user=camunda&password=camunda&characterEncoding=UTF-8&reWriteBatchedInserts=true&ssl=true&sslrootcert=/opt/certs/root.crt&sslcert=/opt/certs/root.crt&sslmode=require
#      DATABASE_URL: jdbc:postgresql://camunda-postgres:5432/camunda?user=camunda&password=camunda&characterEncoding=UTF-8&reWriteBatchedInserts=true
      DATABASE_DRIVER: org.postgresql.Driver
      SERVER_PORT: 9000
      MAX_POOL_SIZE: 3
      MAIL_HOST: mailslurper
      MAIL_PORT: 2500
      RABBITMQ_HOST: rabbitmq-mgmt
      CAMUNDA_HOST: camunda-platform
      CAMUNDA_PORT: 8080
    #      ADMIN_CLIENT_URL: http://camunda-node-1:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
        reservations:
          memory: 1000M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - camunda-postgres
    restart: always
    networks:
      - camunda-cloud
      - camunda-platform