= Camunda Demo Starter

== Quick Start

Follow the steps below to use Docker Compose to quickly start a fully functioning Camunda environment (either version 7 or version 8).

* Create a new directory named `camunda-demo`

 mkdir camunda-demo

* Change into this new directory. (All steps below assume you are in this new `camunda-demo` directory)

 cd camunda-demo

* Now jump to either <<_camunda_8>> or <<_camunda_7>> sections below.

=== Camunda 8

* Clone the `Camunda Platform` project into your local `camunda-demo` directory.

 git clone https://github.com/camunda/camunda-platform.git

* Clone this project (the `camunda-demo-starter` project) into your local `camunda-demo` directory.

 git clone https://github.com/camunda-consulting/camunda-demo-starter.git

* Start a Camunda 8 environment from your `camunda-demo` directory

 cd camunda-demo
 docker-compose -f ./camunda-demo-starter/docker-compose.postgres.yml \
                -f ./camunda-demo-starter/docker-compose.data-api.yml \
                -f ./camunda-demo-starter/docker-compose.reactjs.yml \
                -f ./camunda-demo-starter/docker-compose.smtp.yml \
                -f ./camunda-platform/docker-compose-core.yaml \
                -f ./camunda-demo-starter/docker-compose.c8.yml \
                up -d

* After the environment starts up, access each of the components like so:
** camunda-react: http://localhost:3000
** operate: http://localhost:8082 (TODO: verify this)
*** username/password: demo/demo
** tasklist: http://localhost:8081 (TODO: verify this)
** optimize: http://localhost:8082 (TODO: verify this)
** c8-client: http://localhost:9012 (TODO: verify this)
** data-api: http://localhost:9000 (TODO: verify this)
** camunda-postgres: localhost:5432 (TODO: verify this)
*** username/password: camunda/camunda
** zeebe: localhost: 26500

=== Camunda 7

* Clone this project (the `camunda-demo-starter` project) into your local `camunda-demo` directory

 git clone https://github.com/camunda-consulting/camunda-demo-starter.git

* Start a Camunda 7 environment

 docker-compose  -f ./camunda-demo-starter/docker-compose.postgres.yml
                 -f ./camunda-demo-starter/docker-compose.data-api.yml
                 -f ./camunda-demo-starter/docker-compose.smtp.yml
                 -f ./camunda-demo-starter/docker-compose.c7.yml
                 up -d

* After the environment starts up, access each of the components like so:
** camunda-react: http://localhost:3000
** operate: http://localhost:8082 (TODO: verify this)
*** username/password: demo/demo
** data-api: http://localhost:9000 (TODO: verify this)
** optimize: http://localhost:8082 (TODO: verify this)
** tasklist: http://localhost:8081 (TODO: verify this)
** camunda-postgres: localhost:5432
*** username/password: camunda/camunda

== Presentation Slide Template

https://docs.google.com/presentation/d/1fI7mdW_Q6yEiM0H01b58aQVa74YkTnYj/[Proof of Technology Google Slides Template]

== Components

The Quick Start steps above include the most commonly needed components for demos.

In addition to the default services shown in the "Quick Start" steps above, there are also additional components, such as `camunda-kafka` and/or `camunda-ldap`.

All available components are described in more detail below.

Each component is managed in its own GitHub repository. Here are some suggestions when customizing components:

* Read the documentation on each project below. Fork the project from github into a new repository and checkout into a local project directory.
* Place an enterprise `license.txt` file into the local directory.
* Get enterprise credentials for maven/nexus/jfrog and place them in the `settings.xml`. Copy the `settings.xml` file into your local directory
* TODO: more details on how to create settings.xml file? NOTE: To get credentials you need to create an API key.
* Make your changes and work in your fork.
* TODO: more details on how to start the projects in "development" mode using spring boot profiles
* If you have a contribution that isn't specific to a customer create a pull request.

=== camunda-data-api

TODO: link to github and short description

=== camunda-platform-7-spring-boot

TODO: link to github and short description

=== camunda-7-spring-boot-client

TODO: link to github and short description

=== camunda-8-spring-boot-client

TODO: link to github and short description

=== camunda-react

TODO: link to github and short description

=== camunda-servlet-project

TODO: link to github and short description

=== camunda-tomcat-docker

TODO: link to github and short description

=== camunda-kafka

TODO: link to github and short description

=== camunda-ldap

TODO: link to github and short description

=== camunda-postman

TODO: link to github and short description

=== camunda-dmn-worker

TODO: link to github and short description

=== Authentication and Authorization

TODO: describe using identity for securing the data api and rest apis?

== Documentation IN PROGRESS

TODO: MOVE all the following documentation into appropriate, individual project README's

TIP: Have a look at the docker-compose.<<>>.yml to see the other services you can run and build.

==== Camunda Platform

 Put the license.txt file with your license in the home directory of the project

IMPORTANT: Each project `camunda-data-api-demo`, `camunda-platform-spring-boot`, `camunda-reactjs-demo` each must have a settings.xml with the credentials.


*Build the default apps*

- camunda-platform - localhost:8080
- data-api - localhost:9000
- demo-reactjs - localhost:3000
- camunda-postgres - localhost:5432

```
docker-compose -f docker-compose.c7.yml  -f docker-compose.postgres.yml -f docker-compose.c7-optimize.yml -f docker-compose.data-api.yml  -f docker-compose.reactjs.yml up -d --build camunda-platform optimize data-api reactjs-demo
```

NOTE: It's possible to build and restart only a specific apps to speed up development.

```
 docker-compose -f docker-compose.<<>>.yml up -d --build <service-name>
```

TIP: Have a look at the docker-compose.<<>>.yml to see the other services you can run and build.

====

#### Camunda Platform
====
Camunda Platform in the context of this project is the Camunda Platform as custom embedded Spring-Boot app.

NOTE: Camunda Platform can be run independently of the the other apps. It can also be run in different flavors such as Tomcat with servlet-project. See the docker-compose files in project home.

For convenience there are several prebuilt or preconfigured components to make the poc's and custom demos easier and faster to do. Additionally a standardized file structure is utilized.

- BPMN Workflow Models are in `camunda-platform-spring-boot/src/main/resources/processes/sample.bpmn`

- Reusable delegates are in `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/bpm`

- Integrations are in `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/integration`

- Engine plugins `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/plugin`

- Eventing and messaging `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/pubsub`

- Specific technical use cases and integrations  `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/usecase`

====

//===== CLI
//NOTE: You can enable spring-dev-tools to build front and back-end component in dev mode providing faster restarts and live-reload.
//
//run the app in dev mode by uncommenting spring-dev-tools in pom.xml
//
//WARNING: spring-dev-tools affects the way Camunda serializes objects into process vars and will cause serialization errors in some cases. So it is commented out in pom.xml by default.
//
//run the following with the appropriate profiles
//
//    mvn spring-boot:run -Dspring.profiles.active=poc,email,cors
//
//---

#### Running ReactJS App for Dev
====

IMPORTANT: You may need to install nodejs, nodemon and webpack depending on your environment setup

IMPORTANT: Start the data-api app.

*Configure the api endpoint.*

This is the backend URI for the spring-boot server where the react app gets data

In the .env file in the project home directory change the environment variables to match the spring-boot server context for the data-api.

NOTE: If running the react app as a standalalone and not on localhost configure the API_HOST and API_POST environment vars as follows inserting your host and port for the spring-boot server. You should only need to do this if you cannot access the spring-boot server on localhost and you plan to run the React App standalone.

    API_HOST=http://127.0.0.1
    API_PORT=9000
    API_ROOT=api

IMPORTANT: You will need to use the cors profile in this setup and potentially modify the cors config in the spring-boot app.


Run node and server.js by starting a node server in the home directory of the project. You may need to run `npm install` first.

    nodemon server.js

Run the web-pack watch in the project home so you can update the bundle as you modify reactjs

    webpack -w

IMPORTANT: when demoing or distributing it makse sense to build the reactjs demo with docker-compose. It is built by default. You can also run the docker-compose command

```
 docker-compose -f docker-compose.dev.yml up -d --build reactjs-demo
```
====

#### Developing and Modifying the ReactJS Demo
====
NOTE: Use the instruction above to run the project with NodeJS

The Javascript/JSX files of interest are in the src/main/js folder

The files in `src/main/js/reactjs/application/components` are reusable components

The files in `src/main/js/reactjs/application/usecase` are use case specific components

The file `src/main/js/reactjs/application/app.jsx` is the entry point to the application.

The file

====

#### How the ReactJS Demo project is set up
====
NOTE: This process is done to have a consistent build and utilize features of Spring-Boot. Above is explanation of running the ReactJS in a more traditional way with NodeJS for development.

- Webpack builds/transpile the JSX files into a bundle.js pain of Javascript file

- The bundles.js is copied into `src/main/resources/static/built`

- Spring-boot and the Thymeleaf library are used to serve the ReactJS UI

- Thymeleaf is a spring project for UI templating. It looks in the src/main/resources/templates directory for a .html file to serve. Also a Spring Controller is configured to server the HTML on a specific context path see the controller `src/main/java/com/camunda/poc/starter/controller/ui/UiApplicationController.java`

====


#### Running the data-api server for Dev
====
```
 docker-compose -f docker-compose.dev.yml up -d --build data-api
```
====

#### Modifying and developing the data-api server
====
You need to change this project when you want a new data api to access from your UI or Camunda Worflow. It is a quick way to mock and spin up an api to show a prospect how we can integrate with data and potentially their data model.

Spring, JPA, HATEOS, Lombok are used to quickly build API's that are standardized and reusable.

See the examples in the `src/main/java/com/camunda/poc/starter/data`

You need to create a `config`, `entity` and `Repository` to expose a new API.

NOTE: The ReactJS Demo is configured to use the exposed Data API relatively easily and Camunda project has some Delegate examples.

====



//====
//NOTE: You can enable spring-dev-tools to build front and back-end component in dev mode providing faster restarts and live-reload.
//
//run the app in dev mode by uncommenting spring-dev-tools in pom.xml
//
//WARNING: spring-dev-tools affects the way Camunda serializes objects into process vars and will cause serialization errors in some cases. So it is commented out in pom.xml by default.
//
//run the following with the appropriate profiles
//
//    mvn spring-boot:run -Dspring.profiles.active=poc,email,cors
//====

//#### Kafka

//===== CLI

//==== Using spring-boot profiles
//====
//Start Camunda with Basic Auth on REST api and Authorizations on foe webapps
//
// -Dspring.profiles.active=cors,pubsub,kafka,email,prod,poc,auth,auth-rest"
//
//====