== Demo with this Project

---

=== How to work with this project
- Fork the project from github into a new repository
- Make your changes and work in your fork
- If you have a contribution that isn't specific to a customer create a pull request
- Get an enterprise license

 Put the license.txt file with your license in the home directory of the project

- Get enterprise credentials for maven/nexus/jfrog and place them in the settings.xml file in each project.

IMPORTANT: Each project `camunda-data-api-demo`, `camunda-platform-spring-boot`, `camunda-reactjs-demo` each must have a settings.xml with the credentials.

NOTE: To get credentials you need to create an API key.

### Use the presentation slide template
https://docs.google.com/presentation/d/1fI7mdW_Q6yEiM0H01b58aQVa74YkTnYj/[Proof of Technology Google Slides Template]

===  Get up and running quickly with Docker and Docker Compose

==== Camunda Cloud / C8
====

*Clone the https://github.com/camunda-community-hub/camunda-cloud-docker-compose[Camunda Cloud Docker Compose] project from github*

*Build the apps*

IMPORTANT: make sure to point to the location where you cloned the camunda-cloud-docker-compose

 -f ~/.../camunda-cloud-docker-compose/ccsm-all.yml

```
docker-compose -f docker-compose.c8.yml  -f docker-compose.postgres.yml  -f docker-compose.data-api.yml  -f docker-compose.reactjs.yml  -f ~/.../camunda-cloud-docker-compose/ccsm-all.yml up -d --build c8-client optimize tasklist operate zeebe data-api reactjs-demo
```

- c8-client
- data-api
- demo-reactjs
- camunda-postgres
- optimize
- tasklist
- operate
- zeebe


NOTE: It's possible to build and restart only a specific apps to speed up development.

```
 docker-compose -f docker-compose.<<>>.yml up -d --build <service-name>
```

TIP: Have a look at the docker-compose.<<>>.yml to see the other services you can run and build.

====

==== Camunda Platform
====
*Build the default apps*

- camunda-platform
- data-api
- demo-reactjs
- camunda-postgres

```
docker-compose -f docker-compose.c7.yml  -f docker-compose.postgres.yml -f docker-compose.c7-optimize.yml -f docker-compose.data-api.yml  -f docker-compose.reactjs.yml up -d --build camunda-platform optimize data-api reactjs-demo
```

NOTE: It's possible to build and restart only a specific apps to speed up development.

```
 docker-compose -f docker-compose.<<>>.yml up -d --build <service-name>
```

TIP: Have a look at the docker-compose.<<>>.yml to see the other services you can run and build.

====

#### Camunda Platform
====
Camunda Platform in the context of this project is the Camunda Platform as custom embedded Spring-Boot app.

NOTE: Camunda Platform can be run independently of the the other apps. It can also be run in different flavors such as Tomcat with servlet-project. See the docker-compose files in project home.

For convenience there are several prebuilt or preconfigured components to make the poc's and custom demos easier and faster to do. Additionally a standardized file structure is utilized.

- BPMN Workflow Models are in `camunda-platform-spring-boot/src/main/resources/processes/sample.bpmn`

- Reusable delegates are in `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/bpm`

- Integrations are in `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/integration`

- Engine plugins `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/plugin`

- Eventing and messaging `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/pubsub`

- Specific technical use cases and integrations  `camunda-platform-spring-boot/src/main/java/com/camunda/poc/starter/usecase`

====

//===== CLI
//NOTE: You can enable spring-dev-tools to build front and back-end component in dev mode providing faster restarts and live-reload.
//
//run the app in dev mode by uncommenting spring-dev-tools in pom.xml
//
//WARNING: spring-dev-tools affects the way Camunda serializes objects into process vars and will cause serialization errors in some cases. So it is commented out in pom.xml by default.
//
//run the following with the appropriate profiles
//
//    mvn spring-boot:run -Dspring.profiles.active=poc,email,cors
//
//---

#### Running ReactJS App for Dev
====

IMPORTANT: You may need to install nodejs, nodemon and webpack depending on your environment setup

IMPORTANT: Start the data-api app.

*Configure the api endpoint.*

This is the backend URI for the spring-boot server where the react app gets data

In the .env file in the project home directory change the environment variables to match the spring-boot server context for the data-api.

NOTE: If running the react app as a standalalone and not on localhost configure the API_HOST and API_POST environment vars as follows inserting your host and port for the spring-boot server. You should only need to do this if you cannot access the spring-boot server on localhost and you plan to run the React App standalone.

    API_HOST=http://127.0.0.1
    API_PORT=9000
    API_ROOT=api

IMPORTANT: You will need to use the cors profile in this setup and potentially modify the cors config in the spring-boot app.


Run node and server.js by starting a node server in the home directory of the project. You may need to run `npm install` first.

    nodemon server.js

Run the web-pack watch in the project home so you can update the bundle as you modify reactjs

    webpack -w

IMPORTANT: when demoing or distributing it makse sense to build the reactjs demo with docker-compose. It is built by default. You can also run the docker-compose command

```
 docker-compose -f docker-compose.dev.yml up -d --build reactjs-demo
```
====

#### Developing and Modifying the ReactJS Demo
====
NOTE: Use the instruction above to run the project with NodeJS

The Javascript/JSX files of interest are in the src/main/js folder

The files in `src/main/js/reactjs/application/components` are reusable components

The files in `src/main/js/reactjs/application/usecase` are use case specific components

The file `src/main/js/reactjs/application/app.jsx` is the entry point to the application.

The file

====

#### How the ReactJS Demo project is set up
====
NOTE: This process is done to have a consistent build and utilize features of Spring-Boot. Above is explanation of running the ReactJS in a more traditional way with NodeJS for development.

- Webpack builds/transpile the JSX files into a bundle.js pain of Javascript file

- The bundles.js is copied into `src/main/resources/static/built`

- Spring-boot and the Thymeleaf library are used to serve the ReactJS UI

- Thymeleaf is a spring project for UI templating. It looks in the src/main/resources/templates directory for a .html file to serve. Also a Spring Controller is configured to server the HTML on a specific context path see the controller `src/main/java/com/camunda/poc/starter/controller/ui/UiApplicationController.java`

====


#### Running the data-api server for Dev
====
```
 docker-compose -f docker-compose.dev.yml up -d --build data-api
```
====

#### Modifying and developing the data-api server
====
You need to change this project when you want a new data api to access from your UI or Camunda Worflow. It is a quick way to mock and spin up an api to show a prospect how we can integrate with data and potentially their data model.

Spring, JPA, HATEOS, Lombok are used to quickly build API's that are standardized and reusable.

See the examples in the `src/main/java/com/camunda/poc/starter/data`

You need to create a `config`, `entity` and `Repository` to expose a new API.

NOTE: The ReactJS Demo is configured to use the exposed Data API relatively easily and Camunda project has some Delegate examples.

====



//====
//NOTE: You can enable spring-dev-tools to build front and back-end component in dev mode providing faster restarts and live-reload.
//
//run the app in dev mode by uncommenting spring-dev-tools in pom.xml
//
//WARNING: spring-dev-tools affects the way Camunda serializes objects into process vars and will cause serialization errors in some cases. So it is commented out in pom.xml by default.
//
//run the following with the appropriate profiles
//
//    mvn spring-boot:run -Dspring.profiles.active=poc,email,cors
//====

//#### Kafka

//===== CLI

//==== Using spring-boot profiles
//====
//Start Camunda with Basic Auth on REST api and Authorizations on foe webapps
//
// -Dspring.profiles.active=cors,pubsub,kafka,email,prod,poc,auth,auth-rest"
//
//====