
camunda:
  bpm:
    # Specifies how many times a job will be executed before an incident is raised
    default-number-of-retries: 3
    # If set to true, the job executor will acquire the jobs with the highest priorities
    job-executor-acquire-by-priority: false

    job-execution:
      # If set to false, no JobExecutor bean is created at all. Maybe used for testing.
      enabled: true
      # If job executor is deployment aware
      deployment-aware: false
      # Set to value > 1 to activate parallel job execution
      core-pool-size: 3
      # Specifies the time, in milliseconds, for which threads are kept alive when there are no more tasks present. When the time expires, threads are terminated so that the core pool size is reached.
      keep-alive-seconds: 0
      # Specifies the time in milliseconds an acquired job is locked for execution. During that time, no other job executor can acquire the job.
      lock-time-in-millis: 2000
      # Sets the maximal number of jobs to be acquired at once.
      max-jobs-per-acquisition: 12
      # Maximum number of parallel threads executing jobs.
      max-pool-size: 6
      # Sets the size of the queue which is used for holding tasks to be executed.
      queue-capacity: 12
      # Specifies the wait time of the job acquisition thread in milliseconds in case there are less jobs available for execution than requested during acquisition. If this is repeatedly the case, the wait time is increased exponentially by the factor waitIncreaseFactor. The wait time is capped by maxWait.
      wait-time-in-millis: 3000
      # Specifies the maximum wait time of the job acquisition thread in milliseconds in case there are less jobs available for execution than requested during acquisition.
      max-wait: 10000
      # Specifies the wait time of the job acquisition thread in milliseconds in case jobs were acquired but could not be locked. This condition indicates that there are other job acquisition threads acquiring jobs in parallel. If this is repeatedly the case, the backoff time is increased exponentially by the factor waitIncreaseFactor. The time is capped by maxBackoff. With every increase in backoff time, the number of jobs acquired increases by waitIncreaseFactor as well.
      backoff-time-in-millis: 100
      # Specifies the maximum wait time of the job acquisition thread in milliseconds in case jobs were acquired but could not be locked.
      max-backoff: 10000
      # Specifies the number of successful job acquisition cycles without a job locking failure before the backoff time is decreased again. In that case, the backoff time is reduced by waitIncreaseFacto
      backoff-decrease-threshold: 100
      # Specifies the factor by which wait and backoff time are increased in case their activation conditions are repeatedly met.
      wait-increase-factor: 2
