# Base properties for setting up production environment
# override properties for environments in respective file
# e.g. application-prod.properties for production

#logging.level.com.camunda.*=ERROR

camunda.bpm:
  #  job-execution:
  #    deployment-aware: true
  filter:
    create: All Tasks
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  history-level: none
  jdbcBatchProcessing: none

# How database updates should be handled
#spring.jpa.hibernate.ddl-auto=update

server.port: ${SERVER_PORT}

# data source properties
spring.datasource:
  url: ${DATABASE_URL}
#  type: ${DATASOURCE_TYPE}
  tomcat:
    driver-class-name: ${DATABASE_DRIVER}
    initialSize: 34
    maxActive:  377
    maxIdle:  233
    minIdle: 89
    timeBetweenEvictionRunsMillis: 34000
    minEvictableIdleTimeMillis: 55000
    validationQuery:  SELECT 1
    validationInterval: 34000
    testOnBorrow: true
    removeAbandoned: true
    removeAbandonedTimeout: 55
