# Base properties for setting up production environment
# override properties for environments in respective file
# e.g. application-prod.properties for production

#logging.level.com.camunda.*:ERROR

# How database updates should be handled
#spring.jpa.hibernate.ddl-auto:update

server.port: ${SERVER_PORT}

spring:
  datasource:
    #shareable h2 database
    url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

  h2.console.enabled: true

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none

# Hikari
spring.datasource.hikari.auto-commit: true
spring.datasource.hikari.idle-timeout: 60000
spring.datasource.hikari.max-lifetime: 60000
spring.datasource.hikari.minimum-idle: 2
spring.datasource.hikari.maximum-pool-size: ${MAX_POOL_SIZE}