== [[best-practice-storing-secrets]] Best Practice - Storing Secrets

Problems with secret management that using a Vault addresses

- storing and securly accessing user/password or other sensitive data
- duplication and sprawl of secrets
- automation of secret management
- revoking secrets
- cloud friendly (integration with Kubernetes)
- audit and visibility of secrets
- API progomatic access (Application Access)
- manual access (UI for Humans)

=== Terms

- Passwords, API keys, secure Tokens, and confidential data fall into the category of *secrets*.
- *Token* - Vault works primarily with tokens. Token is assigned to a policy that may constrain the actions and the paths
- *Policy* - Policies use path based matching to apply rules.
- *Authenticaion* - You can create tokens manually and assign them to applications and users. Besides that there are a couple of authentication mechanisms (LDAP, Username/Password, GitHub Token, …) that allow users to login and obtain a token. Tokens and authentication mechanisms can be revoked and that makes it easy to lock out a particular user.
- *Roles* - A role defines the permissions that are associated with the credentials. A role also defines the max lease time for obtained credentials.
- *Lease* - The lease is in Vault-speak the duration the credentials are valid.

=== Requirements

IMPORTANT: Secrets must not be stored in plaintext in any location.

Sensitive data can be encrypted. Encryption imposes the need for decryption on the user side which requires a decryption key to be distributed.

NOTE: Encrypted data is one step better than unencrypted.

Storing a decryption key gives the application the possibility to decrypt data. It also allows an attack vector.

The *Key* is static so a leaked key requires the change of keys. Data needs to be re-encrypted and credentials need to be changed.

TIP: Vault addresses exactly these issues.

 Vault is a service to manage secrets. It provides an API that gives access to secrets based on policies. Any user of the API needs to authenticate and only sees the secrets for which he is authorized. Vault encrypts data using 256-bit AES with GCM. It can store data in various backends (files, Amazon DynamoDB, Consul, etcd and much more). The other key aspect is that Vault never stores a key in a persistent location.

IMPORTANT: Vault isn’t the answer for all security concern. It’s worth to check the https://www.vaultproject.io/docs/internals/security.html[Vault Security Model documentation] to get an idea of the threat model.

=== Setting up Vault

- Download the binary
- Unzip the downloaded file
- Configure Vault
- Start Vault
- set the `VAULT_ADDR` environment variable
- Perform administrative tasks with Vault
- Initialize Vault
- Unseal Vault

=== Setting up Vault with HELM
See https://learn.hashicorp.com/tutorials/vault/kubernetes-minikube?in=vault/kubernetes#install-the-consul-helm-chart[Install Vault in Kubernetes via HELM]

IMPORTANT: If you want to run Camunda and Vault using Kubernetes and the Camunda Docker Image see the section <<run-vault-docker-kubernetes, Running Camunda Docker Image with Vault>>. Please read the entire guide first.

=== Start storing secret data

- Access Vault with authentication token
- Write secret

NOTE: Vault provides the generic secret backend and other backends that allow credential generation for MySQL, SQL Server, PostgreSQL, Consul and https://www.vaultproject.io/docs/secrets/index.html[many more].


IMPORTANT: See the doc https://spring.io/blog/2016/06/24/managing-secrets-with-vault[here] to walk through the steps and setup Vault locally for testing.

=== Spring Cloud Vault

Spring Cloud Vault is a configuration extension which targets external configuration repositories such as Vault. With Spring Cloud Vault you can access your secrets inside Vault.

=== Setting up Camunda Spring-Boot to use Spring Cloud Vault

IMPORTANT: If you want to run Camunda and Vault using Kubernetes and the Camunda Docker Image see the section <<run-vault-docker-kubernetes, Running Camunda Docker Image with Vault>>

- Include the Spring Cloud Vault starter in your project

```XML
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-vault-starter-config</artifactId>
        <version>1.0.0.BUILD-SNAPSHOT</version>
    </dependency>

    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/libs-snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

- Setup the Spring-boot application configuration

```YAML
    spring:
        application:
            name: my-application
        cloud:
            vault:
                token: 9a63de21-8af7-311a-9a5a-151b6a0d4795
                scheme: http
```

- Write data into Vault

  vault write secret/my-application password=H@rdT0Gu3ss

- Update your Spring Boot Application

```JAVA

package example;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringBootVaultHelloWorldApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringBootVaultHelloWorldApplication.class, args);
    }

    @Value("${password}")
    String password;

    @PostConstruct
    private void postConstruct() {
        System.out.println("My password is: " + password);
    }
}

```


=== Vault with Database and Camunda

NOTE: Vault comes with a variety of integrations to different systems. Some of them integrate with PostgreSQL and MySQL as secret backend. Vault can create (and revoke) users for databases on demand.

NOTE: PostgreSQL has built-in support for password expiry with the CREATE ROLE … VALID UNTIL … clause.

==== Setup Vault for Postgres

- Mount Postgres secret backend
- Supply the `Control Connection` details username/password and host/port
- Write the role to Vault
- Generate credentials from role
- Verify using postgres console

NOTE: See the doc https://spring.io/blog/2016/08/15/managing-your-database-secrets-with-vault[here] for details.

==== Setup the Camunda Spring-Boot configuration for Postgres

```YAML
spring.cloud.vault:
		token: 9a63de21-8af7-311a-9a5a-151b6a0d4795
		scheme: http
		generic:
			enabled: false
		mysql:
			enabled: true
			role: readonly

spring.datasource.url: jdbc:postgres://127.0.0.1:3306
```
IMPORTANT: We don’t add any database credentials to the config file. These would usually be spring.datasource.username and spring.datasource.password.

==== Test it's working by adding a bit of code

```JAVA
@SpringBootApplication
public class MySqlApplication {
	public static void main(String[] args) {
		SpringApplication.run(MySqlApplication.class, args);
	}

	@Autowired
	DataSource dataSource;

	@PostConstruct
	private void postConstruct() throws Exception {

		try (Connection connection = dataSource.getConnection();
				Statement statement = connection.createStatement()) {

			ResultSet resultSet = statement.executeQuery("SELECT CURRENT_USER();");
			resultSet.next();

			System.out.println("Connection works with User: " + resultSet.getString(1));

			resultSet.close();
		}
	}
```

NOTE: See the doc https://spring.io/blog/2016/08/15/managing-your-database-secrets-with-vault[here] for more details.


=== [[run-vault-docker-kubernetes]] Using Vault with Camunda Docker Image and Kubernetes via HELM

==== Setting up Vault for Kubernetes

IMPORTANT: Vault running external of a Kubernetes cluster can be addressed by any of its pods as long as the Vault server is network addressable. Running Vault locally alongside of Minikube is possible if the Vault server is bound to the same network as the cluster.

See https://www.vaultproject.io/docs/platform/k8s/helm[Installing Vault Via HELM]

==== Configure and Deploy Static Secret to use with Webapp that interacts with a secured API
See https://learn.hashicorp.com/tutorials/vault/kubernetes-minikube?in=vault/kubernetes[Configuring Vault]

==== Configure dynamic secrets for use with Postgres
https://www.hashicorp.com/blog/dynamic-database-credentials-with-vault-and-kubernetes[See Dynamic DB Credentials with Postgres]

```sh
vault write database/roles/db-app \
    db_name=camunda \
    creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; \
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO \"{{name}}\";" \
    revocation_statements="ALTER ROLE \"{{name}}\" NOLOGIN;"\
    default_ttl="1h" \
    max_ttl="24h"


vault write database/config/camunda \
    plugin_name=postgresql-database-plugin \
    allowed_roles="*" \
    connection_url="postgresql://{{username}}:{{password}}@workflow-database-postgresql.default.svc.cluster.local:5432/workflow?sslmode=disable" \
    username="workflow" \
    password="workflow"

path "database/creds/db-app" {
  capabilities = ["read"]
}z

vault write auth/kubernetes/role/workflow \
    bound_service_account_names=workflow \
    bound_service_account_namespaces=default \
    policies=workflow \
    ttl=24h
```


==== Deploy Camunda with hard coded Vault Address
