### [[kafka-integration]]Kafka Integration
The spring-boot app is using spring cloud streams.

https://spring.io/projects/spring-cloud-stream

====
The app uses a publisher and subscriber for a topic.

```
spring.cloud.stream.bindings.publishWorkflowEvent.destination=service-request-events
spring.cloud.stream.bindings.subscribeWorkflowEvent.destination=service-request-events
```
====

====
A subscriber is implemented `WorkflowEventSubscriber.java` it simply gets the message from the topic and serialized into memory. Then an action can be taken such as saving data, updating the workflow state, etc ...
====

====
A publisher is implemented like `EventPublishingDelegate.java`, other publishers may be needed in your use case. This publisher is also a <<workflow-execution,Cmaunda JavaDelegte>> wired into the bpmn model and executed during the process execution. This is a powerful pattern as it provides control of the workflow execution and allows handling errors, incidents and more.

The publisher publishes an Event with event meta-data such as the Name and Type as well as parameters such as workflow state and business data.

The Event meta-data helps other components understand what to do with the event.
====
