////
===  Handshake Template
Replace following fields in template
- consultant.email
- consultant.name
- csm.email
- Session Schedule
- Location
- List of participants (get this from customer)
////

= <Template> Workshop Handout
Doc Writer <paul.lungu@camunda.com>
v0.3, 2020-05-07
:toc:

== Purpose

== Consultant(s)
* [x] ${consultant.name} Email: mailto:${consultant.email}[${consultant.name}]
* [x] ${consultant.name} Email: mailto:${consultant.email}[${consultant.name}]

== Participants

IMPORTANT: Please update your Camunda contact with the following information

* <Name>  <E-Mail>;
** <Role>
** <Blurb on Technical or Business Background>
** <Level of Camunda Experience> _(e.g. worked with Camunda on past project)_

== Agenda

== Workshop Dates and Times
[%header,format=csv]
|===
SESSION,DATE,TIME
Session 1, 2020-APR-27, 10:00a - 12:00p Eastern Time
Session 2, 2020-APR-27, 1:00p - 4:00p Eastern Time
|===

== Location
*Zoom Bridge*
https://camunda.zoom.us/j/4771146968
```
Meeting ID: 477 114 6968
One tap mobile
+13462487799,,4771146968# US (Houston)
+16699006833,,4771146968# US (San Jose)

Dial by your location
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US
        +1 301 715 8592 US
        +1 312 626 6799 US (Chicago)
        +1 929 205 6099 US (New York)
Meeting ID: 477 114 6968
Find your local number: https://camunda.zoom.us/u/ab7LvWWNJd

```

== Next Steps
* Provide feedback on workshop link:http://survey.com[Survey]
* Contact your CSM to help you determine the best course of action
to ensure your success with Camunda. mailto:${csm.email}[${csm.email}]

== Requirements
IMPORTANT: Things you (customer) must have ready for successful workshop

== Thanks!
I am looking forward to receive your feedback and provide a great workshop
in the coming days. Please feel free to email me with questions or thoughts
before the workshop.

Sincerely,

${consultant.name} mailto:${consultant.email}[${consultant.email}]
